src/Entity/Voiture.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping\PreUpdate;
use Doctrine\ORM\Mapping\PrePersist;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VoitureRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"marque","modele","annee","carburant","etat","prix"},
 * message="Une autre voiture possède déjà exactement les mẽmes attributs marque,modele,annee,
 * carburant,etat,prix. Vérifiez si la voiture n'est pas déjà entrée en base de donnée")
 */
class Voiture
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\NotNull
     */
    private $marque;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $coverImage;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $modele;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     */
    private $annee;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numeroSerie;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $longueur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $largeur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $hauteur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poidsAVide;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $carburant;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $kilometrage;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $couleurCarrosserie;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $couleurInterieur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $puissance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $origine;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $boiteDeVitesse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $moteurEtCylindree;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CvFiscaux;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $conduite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nombreDePlace;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $carrosserie;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank
     */
    private $etat;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="voiture", orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     */
    private $prix;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug()
    {
        $slugify = new Slugify();
        $this->slug = $slugify->slugify(" ".$this->id." "."le"."musée"." ".$this->marque." ".$this->modele." ".$this->carburant." "."année"." ".$this->annee." "."prix"." ".$this->prix."euros"." "."ttc");
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getAnnee(): ?int
    {
        return $this->annee;
    }

    public function setAnnee(int $annee): self
    {
        $this->annee = $annee;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeInterface $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getNumeroSerie(): ?string
    {
        return $this->numeroSerie;
    }

    public function setNumeroSerie(?string $numeroSerie): self
    {
        $this->numeroSerie = $numeroSerie;

        return $this;
    }

    public function getLongueur(): ?string
    {
        return $this->longueur;
    }

    public function setLongueur(?string $longueur): self
    {
        $this->longueur = $longueur;

        return $this;
    }

    public function getLargeur(): ?string
    {
        return $this->largeur;
    }

    public function setLargeur(?string $largeur): self
    {
        $this->largeur = $largeur;

        return $this;
    }

    public function getHauteur(): ?string
    {
        return $this->hauteur;
    }

    public function setHauteur(?string $hauteur): self
    {
        $this->hauteur = $hauteur;

        return $this;
    }

    public function getPoidsAVide(): ?string
    {
        return $this->poidsAVide;
    }

    public function setPoidsAVide(?string $poidsAVide): self
    {
        $this->poidsAVide = $poidsAVide;

        return $this;
    }

    public function getCarburant(): ?string
    {
        return $this->carburant;
    }

    public function setCarburant(string $carburant): self
    {
        $this->carburant = $carburant;

        return $this;
    }

    public function getKilometrage(): ?string
    {
        return $this->kilometrage;
    }

    public function setKilometrage(?string $kilometrage): self
    {
        $this->kilometrage = $kilometrage;

        return $this;
    }

    public function getCouleurCarrosserie(): ?string
    {
        return $this->couleurCarrosserie;
    }

    public function setCouleurCarrosserie(?string $couleurCarrosserie): self
    {
        $this->couleurCarrosserie = $couleurCarrosserie;

        return $this;
    }

    public function getCouleurInterieur(): ?string
    {
        return $this->couleurInterieur;
    }

    public function setCouleurInterieur(?string $couleurInterieur): self
    {
        $this->couleurInterieur = $couleurInterieur;

        return $this;
    }

    public function getPuissance(): ?string
    {
        return $this->puissance;
    }

    public function setPuissance(?string $puissance): self
    {
        $this->puissance = $puissance;

        return $this;
    }

    public function getOrigine(): ?string
    {
        return $this->origine;
    }

    public function setOrigine(?string $origine): self
    {
        $this->origine = $origine;

        return $this;
    }

    public function getBoiteDeVitesse(): ?string
    {
        return $this->boiteDeVitesse;
    }

    public function setBoiteDeVitesse(?string $boiteDeVitesse): self
    {
        $this->boiteDeVitesse = $boiteDeVitesse;

        return $this;
    }

    public function getMoteurEtCylindree(): ?string
    {
        return $this->moteurEtCylindree;
    }

    public function setMoteurEtCylindree(?string $moteurEtCylindree): self
    {
        $this->moteurEtCylindree = $moteurEtCylindree;

        return $this;
    }

    public function getCvFiscaux(): ?string
    {
        return $this->CvFiscaux;
    }

    public function setCvFiscaux(?string $CvFiscaux): self
    {
        $this->CvFiscaux = $CvFiscaux;

        return $this;
    }

    public function getConduite(): ?string
    {
        return $this->conduite;
    }

    public function setConduite(?string $conduite): self
    {
        $this->conduite = $conduite;

        return $this;
    }

    public function getNombreDePlace(): ?string
    {
        return $this->nombreDePlace;
    }

    public function setNombreDePlace(?string $nombreDePlace): self
    {
        $this->nombreDePlace = $nombreDePlace;

        return $this;
    }

    public function getCarrosserie(): ?string
    {
        return $this->carrosserie;
    }

    public function setCarrosserie(?string $carrosserie): self
    {
        $this->carrosserie = $carrosserie;

        return $this;
    }

    public function getetat(): ?string
    {
        return $this->etat;
    }

    public function setetat(?string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(?string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

src/Form/VoitureType.php
<?php

namespace App\Form;

use App\Entity\Image;
use App\Entity\Voiture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class VoitureType extends AbstractType
{
    /**
     * Permet d'avoir la configuration de base d'un champ
     *
     * @param string $label
     * @param string $placeholder
     * @param array $options
     * @return array
     */
    private function getConfiguration($label, $placeholder, $options = [])
    {
        return array_merge([
            'label' => $label,
            'attr' => [
                'placeholder' => $placeholder
            ]
        ], $options);
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('marque', TextType::class, $this->getConfiguration("Marque  /!\Requis/!\ ", "Ex: Ferrari"))
            ->add('modele', TextType::class, $this->getConfiguration("Modèle  /!\Requis/!\ ", "Ex: 328 GTS"))
            ->add('carburant', TextType::class, $this->getConfiguration("Carburant  /!\Requis/!\ ", " Ex: Essence"))
            ->add('annee', IntegerType::class, $this->getConfiguration("Année  /!\Requis/!\ ", "Ex: 1968"))
            ->add('etat', TextType::class, $this->getConfiguration("Etat  /!\Requis/!\ ", "Ex: parfait état"))
            ->add('prix', MoneyType::class, $this->getConfiguration("Prix TTC  /!\Requis/!\ ", "Ex: 45000"))
            ->add('introduction', TextType::class, $this->getConfiguration("Introduction de l'annonce  /!\Requis/!\ ", "Ex: La Ferrari 328 remplace le Ferrari 308 en septembre 1985 au Salon automobile de Francfort...", ['attr' => ['class' => 'ckeditor']]))
            ->add('content', TextareaType::class, $this->getConfiguration("Contenue de l'annonce  /!\Requis/!\ ", "Ex: La Ferrari 328 remplace le Ferrari 308 en septembre 1985 au Salon automobile de Francfort. Les pare-chocs avant et arrière sont plus enveloppants et peints ton caisse et se dote d’un aileron arrière......", ['attr' => ['class' => 'ckeditor']]))
            ->add('type', TextType::class, $this->getConfiguration("Type", " Ex: F106ASR", [ 'required' => false ]))
            ->add('numeroSerie', TextType::class, $this->getConfiguration("Numéro de série", "Ex: ZFFWA20B000073991", [ 'required' => false ]))
            ->add('longueur', TextType::class, $this->getConfiguration("Longueur", "Ex: 426 CM", [ 'required' => false ]))
            ->add('largeur', TextType::class, $this->getConfiguration("Largeur", "Ex: 173 CM", [ 'required' => false ]))
            ->add('hauteur', TextType::class, $this->getConfiguration("Hauteur", "Ex: 113 CM", [ 'required' => false ]))
            ->add('poidsAVide', TextType::class, $this->getConfiguration("Poids à vide", " Ex: 1273 KG", [ 'required' => false ]))
            ->add('kilometrage', TextType::class, $this->getConfiguration("Kilomètrage", "Ex: 52039 Km", [ 'required' => false ]))
            ->add('puissance', TextType::class, $this->getConfiguration("Puissance", "Ex: 320 ch", [ 'required' => false ]))
            ->add('origine', TextType::class, $this->getConfiguration("Origine", "Ex: Italie", [ 'required' => false ]))
            ->add('boiteDeVitesse', TextType::class, $this->getConfiguration("Boite de vitesse", "Ex: automatique", [ 'required' => false ]))
            ->add('moteurEtCylindree', TextType::class, $this->getConfiguration("Moteur & Cylindrée", "Ex: V8 - 390 ci - 6,4 L", [ 'required' => false ]))
            ->add('CvFiscaux', TextType::class, $this->getConfiguration("CV fiscaux", "Ex: 37 cv", [ 'required' => false ]))
            ->add('conduite', TextType::class, $this->getConfiguration("Conduite", "Ex: à droite", [ 'required' => false ]))
            ->add('nombreDePlace', TextType::class, $this->getConfiguration("Nombre de place", "Ex: 4", [ 'required' => false ]))
            ->add('couleurCarrosserie', TextType::class, $this->getConfiguration("Couleur carrosserie", "Ex: Wimbledon white", [ 'required' => false ]))
            ->add('couleurInterieur', TextType::class, $this->getConfiguration("Couleur intérieur", "Ex: rouge", [ 'required' => false ]))
            ->add('carrosserie', TextType::class, $this->getConfiguration("Carrosserie", "Ex: Fastback", [ 'required' => false ]))
            ->add('coverImage', FileType::class, [ 'label' => 'Ajoutez une photo de la voiture pour la couverture', 'data_class' => null ])
            ->add('files', FileType::class, [ 'label' => 'Ajoutez des photos de la voiture pour l\'annonce  /!\Maintenez la touche "ctrl" pour sélectionner plusieures photos/!\ ','mapped' => false, 'multiple' => true, 'data_class' => null])
            ->add('Enregistrer', SubmitType::class,[
                'attr' => ['class' => 'btn btn-success']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Voiture::class
        ]);
    }
}

src/Controller/VoitureController.php
<?php

namespace App\Controller;

use App\Repository\ImageRepository;
use App\Repository\VoitureRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\Voiture;

class VoitureController extends AbstractController
{
    /**
     * Liste des voitures
     * @Route("/voitures", name="voitures_index")
     */
    public function index(VoitureRepository $repoVoiture)
    {
        $voitures = $repoVoiture->findAll(); 

        foreach ($voitures as $voiture) 
        {
            $ids[] = $voiture->getId();
        }
        array_multisort($ids, SORT_DESC, $voitures);
        
        return $this->render('voiture/index.html.twig', [
            'voitures' => $voitures
        ]);
    }

    /**
     * Permet d'afficher le descriptif complet d'une voiture
     *
     * @Route("/voitures/{slug}", name="voitures_show")
     * 
     * @return Response
     */
    public function show(Voiture $voiture)
    {   
        return $this->render('voiture/show.html.twig', [
            'voiture' => $voiture
        ]);
    }
}

templates/voiture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Notre Parc{% endblock %}

{% block body %}
<div class="container">
    <div class="shadow-lg p-3 mb-5 bg-white rounded">
        <h1 class="text-center my-5">Bienvenue dans notre Parc</h1>
        
        <h5 class="text-center my-5 ">
            Toute fois, si vous ne trouvez pas le vehicule de vos rêves dans ce listing,<br><br>
            n’hesitez surtout pas à nous <a href="{{ path('contact') }}" style="color: rgb(214, 0, 0)"> contacter</a>. <br><br><br>
            
            Grace à nos collaborateurs à l’international et nos deplacements trimestriels,<br><br>
            nous pouvons trouver votre vehicule de collection restaure, ou à restaurer.<br><br><br>

            Nous selectionnons pour vous, selon vos desirs et votre budget,<br><br>
            les vehicules correspondant à vos attentes.<br><br>
        </h5>
    </div>
    <div class="row">
        {% for voiture in voitures %}
            {% set url = path('voitures_show',{'slug': voiture.slug}) %}

            <div class="col-md-4 my-2">
                <div class="card border-secondary mb-3">
                    <div class="card-header text-center">
                        Prix <span>{{ voiture.prix }}&euro;</span>/TTC<br><small>En {{ voiture.etat }}</small>
                    </div>
                    <div id="carouselExampleSlidesOnly" class="carousel slide carousel-fade" data-interval="3000" data-ride="carousel">
                        <div class="carousel-inner">
                            {% for image in voiture.images %}
                                <div class="carousel-item {% if loop.first %} active {% endif %}">
                                    <a href="{{ url }}" target="_blank">
                                        <img src="/uploads/{{image.url}}" style="height: 240px; width: 100%; display: block" class="d-block w-100" style="height: 180px; width: auto; display: block" alt="{{ voiture.slug }}">
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="card-body">
                        <a href="{{ url }}" target="_blank">
                            <h4 class="card-title">{{ voiture.marque }} {{ voiture.modele }} {% if voiture.type %} {{ voiture.type }} {% endif %}</h4>
                        </a>
                        <p class="card-text">{{ voiture.Introduction | raw}}</p>
                        <a href="{{ url }}" class="btn btn-primary" target="_blank">En savoir plus !</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/voiture/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {{ voiture.marque }}
    {{ voiture.modele }}{% if voiture.type %}
        {{ voiture.type }}
    {% endif %}
{% endblock %}
{% block body %}
    <div class="voiture-title" style="background-image: url('/uploads/{{ voiture.coverImage }}')">
        <div class="row">
            <div class="col-md-9">
                <h1 class="my-3">
                    {{ voiture.marque }}
                    {{ voiture.modele }}
                    {% if voiture.type %}
                        {{ voiture.type }}
                    {% endif %}
                </h1>
                <p>
                    {{ voiture.introduction }}</p>
                <p class="h2">
                    <small>{{ voiture.etat }}</small>
                </p>
            </div>
            <div class="col-md-3 mt-5">
                <div class="mt-4">
                    <a class="btn btn-primary mt-5 p-3" href="{{ path('contact_voiture', {'slug': voiture.slug}) }}">Demandez plus d'info</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                <p class="text-primary">{{ voiture.content | raw}}</p>
                <div class="carousel slide carousel-fade my-3" data-ride="carousel" id="carouselExampleIndicators">
                    <ol class="carousel-indicators">
                        {% for image in voiture.images %}
                            <li data-target="#carouselExampleIndicators" data-slide-to=" {{loop.index0 }} " class="{% if loop.first %} active {% endif %}"></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in voiture.images %}
                            <div class="carousel-item {% if loop.first %} active {% endif %}">
                                <img src="/uploads/{{image.url}}" class="d-block w-100" alt="{{ voiture.slug }}">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h5>
                                            {{ voiture.marque }}
                                            {{ voiture.modele }}
                                            {% if voiture.type %}
                                                {{ voiture.type }}
                                            {% endif %}
                                        </h5>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" data-slide="prev" href="#carouselIndicators" role="button">
                            <span aria-hidden="true" class="carousel-control-prev-icon"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" data-slide="next" href="#carouselExampleIndicators" role="button">
                            <span aria-hidden="true" class="carousel-control-next-icon"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    <div class="fb-like" data-action="like" data-href="http://www.le-musee.fr/voitures/{{ voiture.marque }}" data-layout="button_count" data-share="true" data-show-faces="true" data-size="small"></div>
                </div>
                <div class="col my-1">
                    <div class="card bg-primary mb-3">
                        <div class="card-body">
                            <h3 class="text-center text-white my-1">Prix TTC:
                                <span>
                                    {{ voiture.prix }}&euro;</span>
                            </h3>
                        </div>
                    </div>
                    <h5 class="text-center">Caractéristiques :</h5>
                    <div class="row mt-3">
                        <table class="table table-sm table-striped table-hover table-dark">
                            <tbody>
                                <tr>
                                    <td>Marque</td>
                                    <td>
                                        {{ voiture.marque }}</td>
                                </tr>
                                <tr>
                                    <td>Modele</td>
                                    <td>
                                        {{ voiture.modele }}</td>
                                </tr>
                                {% if voiture.type %}
                                    <tr>
                                        <td>Type</td>
                                        <td>
                                            {{ voiture.type }}</td>
                                    </tr>
                                {% endif %}
                                <tr>
                                    <td>Carburant</td>
                                    <td>
                                        {{ voiture.carburant }}</td>
                                </tr>
                                <tr>
                                    <td>Annee</td>
                                    <td>
                                        {{ voiture.annee }}</td>
                                </tr>
                                {% if voiture.numeroSerie %}
                                    <tr>
                                        <td>N° de serie</td>
                                        <td>
                                            {{ voiture.numeroSerie }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.origine %}
                                    <tr>
                                        <td>Origine</td>
                                        <td>
                                            {{ voiture.origine }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.kilometrage %}
                                    <tr>
                                        <td>Kilometrage</td>
                                        <td>
                                            {{ voiture.kilometrage }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.cvFiscaux %}
                                    <tr>
                                        <td>CV fiscaux</td>
                                        <td>
                                            {{ voiture.cvFiscaux }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.moteurEtCylindree %}
                                    <tr>
                                        <td>Moteur & Cylindree</td>
                                        <td>
                                            {{ voiture.moteurEtCylindree }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.puissance %}
                                    <tr>
                                        <td>Puissance</td>
                                        <td>
                                            {{ voiture.puissance }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.boiteDeVitesse %}
                                    <tr>
                                        <td>Boite de vitesse</td>
                                        <td>
                                            {{ voiture.boiteDeVitesse }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.nombreDePlace %}
                                    <tr>
                                        <td>Nombre de place</td>
                                        <td>
                                            {{ voiture.nombreDePlace }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.conduite %}
                                    <tr>
                                        <td>Conduite</td>
                                        <td>
                                            {{ voiture.conduite }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.carrosserie %}
                                    <tr>
                                        <td>Carrosserie</td>
                                        <td>
                                            {{ voiture.carrosserie }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.couleurCarrosserie %}
                                    <tr>
                                        <td>Couleur carrosserie</td>
                                        <td>
                                            {{ voiture.couleurCarrosserie }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.couleurInterieur %}
                                    <tr>
                                        <td>Couleur interieur</td>
                                        <td>
                                            {{ voiture.couleurInterieur }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.longueur %}
                                    <tr>
                                        <td>Longueur</td>
                                        <td>
                                            {{ voiture.longueur }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.largeur %}
                                    <tr>
                                        <td>Largeur</td>
                                        <td>
                                            {{ voiture.largeur }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.hauteur %}
                                    <tr>
                                        <td>Hauteur</td>
                                        <td>
                                            {{ voiture.hauteur }}</td>
                                    </tr>
                                {% endif %}
                                {% if voiture.poidsAVide %}
                                    <tr>
                                        <td>Poids à vide</td>
                                        <td>
                                            {{ voiture.poidsAVide }}</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}